# docker-compose.yml

version: "3.8"

services:
  backend:
    build: ./server
    container_name: backend
    image: mern-back
    ports:
      - "5003:5003"
    env_file:
      - ./server/.env
    networks:
      - mern

  frontend:
    build: ./client
    container_name: frontend
    image: mern-front
    ports:
      - "5173:5173"
    networks:
      - mern
    depends_on:
      - backend

networks:
  mern:
    driver: bridge
